apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: debug
  labels:
    team: aura
spec:
  image: vegarm/debug:2
  port: 8080
  replicas:
    min: 1
    max: 1
  skipCaBundle: true
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: google.com
